
development:
  adapter: postgresql
  encoding: unicode
  database: dynamic_select_boxes_development
  pool: 5
  username: postgres
  password: admin  

test:
  adapter: postgresql
  encoding: unicode
  database: dynamic_select_boxes_test
  pool: 5
  username: postgres
  password: admin

production:
  adapter: postgresql
  encoding: unicode
  database: dynamic_select_boxes_production
  pool: 5
  username: postgres
  password: admin
